name: Run Python linter
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.2
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Download Google style guide, amend indentations
      run: |
        wget https://google.github.io/styleguide/pylintrc -O .pylintrc
        sed -i "s/indent-string='  '/indent-string='    '/" .pylintrc
    - name: Analyze code with pylint
      run: |
        pylint --rcfile=.pylintrc --fail-under=10 **/*.py
